// children/svelte-child-2/src/components/Content.svelte
<style lang="scss">
  @import "src/styles/common";

  .Content {
    display: flex;
    flex-direction: column;
    background-color: $color-secondary;

    @include border-heavy;

    .title {
      display: flex;
      flex-direction: row;
      justify-content: center;

      h1 {
        text-align: center;
      }
    }

    .content {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    }
  }
</style>

<script>
    import { Route, useLocation, useNavigate } from 'svelte-navigator';
    import UserList from './UserList.svelte';
    import UserDetails from './UserDetails.svelte';
    import axios from 'axios';
    import { onDestroy, onMount } from 'svelte';

    let users = [];

    const navigate = useNavigate();
    const location = useLocation();
    const locationUnsubscribe = location.subscribe((locationDetails) => {
        if (locationDetails.pathname === '/') {
            navigate('/0');
        }
    });

    onMount(() => {
        axios.get('https://reqres.in/api/users')
            .then((res) => {
                users = res.data.data;
            })
            .catch((ex) => console.error(ex));
    });

    onDestroy(() => {
        locationUnsubscribe();
    });
</script>

<div class="Content">
    <div class="title">
        <h1>Svelte Child 2</h1>
    </div>
    <Route path="/:userId">
        <div class="content">
            <UserList users={ users } />
            <UserDetails users={ users } />
        </div>
    </Route>
</div>

// children/vue-child-1/src/components/Content.vue
<template>
  <div class="Content">
    <h1>Vue Child 1</h1>
    <router-view :users="users" />
  </div>
</template>

<script>
import { onMounted, ref } from 'vue';
import axios from 'axios';

export default {
  name: "Content",
  setup() {
    const users = ref([]);

    onMounted(() => {
      axios.get('https://reqres.in/api/users')
          .then((res) => users.value = res.data.data)
          .catch((ex) => console.error(ex));
    });

    return {
      users
    };
  }
}
</script>

<style scoped lang="scss">
  @import "src/styles/common";
  .Content {
    display: flex;
    flex-direction: column;
    background-color: $color-secondary;
    @include border-heavy;

    .title {
      display: flex;
      flex-direction: row;
      justify-content: center;

      h1 {
        text-align: center;
      }
    }
  }
</style>
