// children/svelte-child-1/src/components/UserDetails.svelte
<style lang="scss">
  @import "src/styles/common";

  .UserDetails {
    margin: 1rem;
    padding: 2rem;
    font-size: $text-size-content;

    @include border-light;

    :global(textarea) {
      width: 100%;
      height: 10rem;
      resize: none;
    }
  }
</style>

<script>
    import { createGetSelectedUser } from './createGetSelectedUser';
    const { subscribe, updateState, getState } = await import('globalStore').catch((ex) => alert(ex.message));
    import { afterUpdate, onDestroy } from 'svelte';

    export let users = [];

    const getSelectedUser = createGetSelectedUser();
    $: selectedUser = getSelectedUser(users);
    let notes = '';

    let oldSelectedUser = null;
    $: if (oldSelectedUser !== selectedUser) {
        notes = getState().userNotes?.[selectedUser?.id] ?? '';
        oldSelectedUser = selectedUser;
    }

    const storeUnsubscribe = subscribe((state) => {
        notes = state.userNotes?.[selectedUser?.id] ?? '';
    });

    onDestroy(() => {
        storeUnsubscribe();
    });

    const updateNotes = (text) => updateState((draft) => {
        const userNotes = draft.userNotes ?? {};
        userNotes[selectedUser.id] = text;
        draft.userNotes = userNotes;
    });
</script>

<div class="UserDetails">
    {#if selectedUser !== null}
        <img src={ selectedUser?.avatar } alt="avatar" />
    {/if}
    <p>
        <strong>Name: </strong>
        { selectedUser?.first_name ?? '' } { selectedUser?.last_name ?? '' }
    </p>
    <p>
        <strong>Email: </strong>
        { selectedUser?.email ?? '' }
    </p>
    <span>
        <strong>Notes:</strong>
    </span>
    {#if selectedUser !== null}
        <textarea
                value={ notes }
                on:input={ (event) => updateNotes(event.target.value) }
        />
    {/if}
</div>

// children/vue-child-1/src/components/UserDetails.vue
<template>
  <div class="UserDetails">
    <img v-if="!!selectedUser" :src="selectedUser?.avatar" alt="avatar" />
    <p>
      <strong>Name: </strong>
      {{ selectedUser?.first_name }} {{ selectedUser?.last_name }}
    </p>
    <p>
      <strong>Email: </strong>
      {{ selectedUser?.email }}
    </p>
    <span>
      <strong>Notes:</strong>
    </span>
    <textarea v-if="!!selectedUser" />
  </div>
</template>

<script>
import { useSelectedUser } from './useSelectedUser';
import { onMounted, onUnmounted, ref } from 'vue';
import { subscribe, updateState } from 'globalStore';

export default {
  props: [
      'users'
  ],
  setup(props) {
    const selectedUser = useSelectedUser(props.users);
    const notes = ref('');

    let storeUnsubscribe;

    onMounted(() => {
      storeUnsubscribe = subscribe((state) => {
        notes.value = state.userNotes?.[selectedUser?.value?.id] ?? '';
      });
    });

    onUnmounted(() => {
      if (storeUnsubscribe) {
        storeUnsubscribe();
      }
    });

    return {
      selectedUser
    }
  }
}
</script>

<style scoped lang="scss">
  @import "src/styles/common";

  .UserDetails {
    margin: 1rem;
    padding: 2rem;
    font-size: $text-size-content;

    @include border-light;

    textarea {
      width: 100%;
      height: 10rem;
      resize: none;
    }
  }
</style>
