// children/svelte-child-1/src/components/App.svelte
<script>
    import { Router } from 'svelte-navigator';
    import Content from './Content.svelte';
    import { GlobalRouterConnector } from '@mfdemo/global-router-svelte-navigator/src';

    // TODO primary=false might not be necessary
</script>

<Router primary={ false }>
    <GlobalRouterConnector />
    <Content />
</Router>

// children/vue-child-2/src/components/App.vue
<template>
  <GlobalRouterConnector />
  <Content />
</template>

<script>
import Content from './Content';
// TODO why do I need to only import it from src here?
import { GlobalRouterConnector } from '@mfdemo/global-router-vue-router/src';
export default {
  name: "App",
  components: { Content, GlobalRouterConnector }
}
</script>

<style scoped>

</style>
