// children/svelte-child-1/src/components/Content.svelte
<style lang="scss">
  @import "src/styles/common";

  .Content {
    display: flex;
    flex-direction: column;
    background-color: $color-secondary;

    @include border-heavy;

    .title {
      display: flex;
      flex-direction: row;
      justify-content: center;

      h1 {
        text-align: center;
      }
    }

    .content {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    }
  }
</style>

<script>
    import { Route, useLocation, useNavigate } from 'svelte-navigator/src/index';
    import UserList from './UserList.svelte';
    import UserDetails from './UserDetails.svelte';
    import axios from 'axios';
    import { onDestroy, onMount } from 'svelte';

    let users = [];

    const navigate = useNavigate();
    const location = useLocation();
    const locationUnsubscribe = location.subscribe((locationDetails) => {
        console.log('Location', locationDetails.pathname); // TODO delete this
        if (locationDetails.pathname === '/') {
            navigate('/0');
        }
    });

    onMount(() => {
        axios.get('https://reqres.in/api/users')
            .then((res) => {
                users = res.data.data;
            })
            .catch((ex) => console.error(ex));
    });

    onDestroy(() => {
        locationUnsubscribe();
    });
</script>

<div class="Content">
    <div class="title">
        <h1>Svelte Child 1</h1>
    </div>
    <Route path="/:userId">
        <div class="content">
            <UserList users={ users } />
            <UserDetails users={ users } />
        </div>
    </Route>
</div>

// applications/react-child-1/src/components/Content.js
import { useEffect, useState } from 'react';
import classes from './Content.module.scss';
import { UserList } from './UserList';
import { UserDetails } from './UserDetails';
import axios from 'axios';
import { Route, useLocation } from 'react-router';

export const Content = () => {
    const location = useLocation();
    console.log(location); // TODO delete this
    const [state, setState] = useState({
        users: []
    });

    useEffect(() => {
        const request = async () => {
            const res = await axios.get('https://reqres.in/api/users');
            setState((prevState) => ({
                ...prevState,
                users: res.data.data
            }));
        };
        request();
    }, []);

    return (
        <div className={ classes.Content }>
            <div className={ classes.title }>
                <h1>React Child 1</h1>
            </div>
            <div className={ classes.content }>
                <UserList
                    users={ state.users }
                />
                <Route
                    path="/:userId"
                    render={ () => (
                        <UserDetails
                            users={ state.users }
                        />
                    ) }
                />
            </div>
        </div>
    );
};
