// applications/svelte-child-1/src/components/Content.svelte
<style lang="scss">
  .Content {
    display: flex;
    flex-direction: column;
    background-color: lightgreen;
    border: 3px solid darkgreen;
    border-radius: 5px;

    .title {
      display: flex;
      flex-direction: row;
      justify-content: center;

      h1 {
        text-align: center;
      }
    }

    .content {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    }
  }
</style>

<script>
    import { Route, useLocation, useNavigate } from 'svelte-navigator/src/index';
    import UserList from './UserList.svelte';
    import UserDetails from './UserDetails.svelte';
    import axios from 'axios';
    import { onMount } from 'svelte';

    let users = [];

    const navigate = useNavigate();
    const location = useLocation();
    location.subscribe((locationDetails) => {
        if (locationDetails.pathname === '/') {
            navigate('/0');
        }
    });

    onMount(() => {
        axios.get('https://reqres.in/api/users')
            .then((res) => {
                users = res.data.data;
            })
            .catch((ex) => console.error(ex));
    });
</script>

<div class="Content">
    <div class="title">
        <h1>Svelte Child 1</h1>
    </div>
    <Route path="/:userId">
        <div class="content">
            <UserList users={ users } />
            <UserDetails users={ users } />
        </div>
    </Route>
</div>

// children/react-child-2/src/components/Content.js
import { useEffect, useState } from 'react';
import classes from './Content.module.scss';
import { UserList } from './UserList';
import { UserDetails } from './UserDetails';
import axios from 'axios';
import { Redirect, Route, Switch } from 'react-router';

export const Content = () => {
    const [state, setState] = useState({
        users: []
    });

    useEffect(() => {
        axios.get('https://reqres.in/api/users')
            .then((res) => setState((prevState) => ({
                ...prevState,
                users: res.data.data
            })))
            .catch((ex) => console.error(ex));
    }, []);

    return (
        <div className={ classes.Content }>
            <div className={ classes.title }>
                <h1>React Child 1</h1>
            </div>
            <Switch>
                <Route
                    path="/:userId"
                    render={ () => (
                        <div className={ classes.content }>
                            <UserList
                                users={ state.users }
                            />
                            <UserDetails
                                users={ state.users }
                            />
                        </div>
                    ) }
                />
                <Redirect to="/0" />
            </Switch>
        </div>
    );
};
