// utilities/global-router-svelte-navigator/src/GlobalRouterConnector.svelte
<script>
    import { useLocation, useNavigate } from 'svelte-navigator';
    import { onDestroy } from 'svelte';

    const EVENT_NAME = 'microFrontendGlobalRouter';

    let currentPathname = '';
    let dispatching = false;

    const location = useLocation();
    const navigate = useNavigate();

    const globalRouterListener = (event) => {
        if (!dispatching) {
            currentPathname = event.detail.pathname;
            navigate(event.detail.pathname);
        } else {
            dispatching = false;
        }
    };

    const locationUnsubscribe = location.subscribe((locationDetails) => {
        if (currentPathname !== locationDetails.pathname) {
            const event = new CustomEvent(EVENT_NAME, {
                detail: {
                    pathname: locationDetails.pathname
                }
            });
            dispatching = true;
            window.dispatchEvent(event);
        }
        currentPathname = locationDetails.pathname;
    });

    window.addEventListener(EVENT_NAME, globalRouterListener, true);

    onDestroy(() => {
        locationUnsubscribe();
        window.removeEventListener(EVENT_NAME, globalRouterListener, true);
    });

</script>

<span></span>

// utilities/global-router-vue-router/src/GlobalRouterConnector.vue
<template>
  <span></span>
</template>

<script>
import { useRoute, useRouter } from 'vue-router';
import { onUnmounted, watch } from 'vue';

const EVENT_NAME = 'microFrontendGlobalRouter';

export default {
  setup() {
    const route = useRoute();
    const router = useRouter();

    let dispatching = false;
    let currentPathname = '';

    const globalRouterListener = (event) => {
      if (!dispatching) {
        currentPathname = event.detail.pathname;
        router.push(event.detail.pathname);
      } else {
        dispatching = false;
      }
    };

    const routeUnsubscribe = watch(route, (newValue, oldValue) => {
      if (currentPathname !== newValue.path) {
        const event = new CustomEvent(EVENT_NAME, {
          detail: {
            pathname: newValue.path
          }
        });
        dispatching = true;
        window.dispatchEvent(event);
      }
      currentPathname = newValue.path;
    });
    window.addEventListener(EVENT_NAME, globalRouterListener, true);

    onUnmounted(() => {
      routeUnsubscribe();
      window.removeEventListener(EVENT_NAME, globalRouterListener, true);
    });
  }
}
</script>

<style scoped>

</style>
