// children/vue-child-1/src/components/UserList.vue
<template>
  <div class="UserList">
    <ul>
      <router-link v-for="user in users" :to="`/${user.id}`">
        <li>
          {{ user.first_name }} {{ user.last_name }}
        </li>
      </router-link>
    </ul>
  </div>
</template>

<script>
export default {
  props: [
      'users'
  ],
  setup(props) {

  }
}
</script>

<style scoped lang="scss">
  @import "src/styles/common";

  .UserList {
    margin: 1rem;

    ul {
      list-style: none;
      margin: 0;
      padding: 0;

      a {
        text-decoration: none;
        color: inherit;
      }

      li {
        font-size: $text-size-content;
        padding: 1rem;
        cursor: pointer;

        @include border-light;

        &:hover {
          background-color: $color-primary;
          color: white;
        }

        &.active {
          background-color: $color-primary;
          color: white;
        }
      }
    }
  }
</style>

// applications/svelte-child-1/src/components/UserList.svelte
<style lang="scss">
  @import "src/styles/common";

  .UserList {
    margin: 1rem;

    ul {
      list-style: none;
      margin: 0;
      padding: 0;

      :global(a) {
        text-decoration: none;
        color: inherit;
      }

      :global(li) {
        font-size: $text-size-content;
        padding: 1rem;
        cursor: pointer;

        @include border-light;

        &:hover {
          background-color: $color-primary;
          color: white;
        }

        &.active {
          background-color: $color-primary;
          color: white;
        }
      }
    }
  }
</style>

<script>
    import { Link, useParams } from 'svelte-navigator';

    export let users = [];

    let userId = 0;
    const params = useParams();
    params.subscribe((paramDetails) => {
        userId = paramDetails.userId ? parseInt(paramDetails.userId) : 0;
    });
</script>

<div class="UserList">
    <ul>
        {#each users as user}
            <Link to={ `/${user.id}` }>
                <li class:active={ user.id === userId }>
                    { user.first_name } { user.last_name }
                </li>
            </Link>
        {/each}
    </ul>
</div>
