// applications/react-child-1/src/components/UserDetails.js
import classes from './UserDetails.module.scss';
import { userPropType } from '../propTypes/userPropType';
import PropTypes from 'prop-types';
import { useRouteMatch } from 'react-router';
import { useMemo } from 'react';

export const UserDetails = (props) => {
    const match = useRouteMatch();
    const selectedUser = useMemo(() =>
            props.users.find((user) => user.id === parseInt(match.params.userId)),
        [match.params.userId, props.users]);

    return (
        <div className={ classes.UserDetails }>
            {
                selectedUser &&
                <img src={ selectedUser?.avatar } alt="avatar" />
            }
            <p>
                <strong>Name: </strong>
                { selectedUser?.first_name } { selectedUser?.last_name }
            </p>
            <p>
                <strong>Email: </strong>
                { selectedUser?.email }
            </p>
        </div>
    );
};
UserDetails.propTypes = {
    users: PropTypes.arrayOf(userPropType).isRequired
};

// applications/svelte-child-1/src/components/UserDetails.svelte
<style lang="scss">
  @import "src/styles/common";

  .UserDetails {
    margin: 1rem;
    padding: 2rem;
    font-size: $text-size-content;

    @include border-light;

    :global(textarea) {
      width: 100%;
      height: 10rem;
      resize: none;
    }
  }
</style>

<script>
    import { useParams } from 'svelte-navigator';
    import { onDestroy } from 'svelte';

    const params = useParams();

    export let users = [];
    let oldUsers = [];

    let userId = 0;
    let selectedUser = null;
    const paramsUnsubscribe = params.subscribe((paramDetails) => {
        userId = paramDetails.userId ? parseInt(paramDetails.userId) : 0;
    });

    $: if (users !== oldUsers) {
        selectedUser = users.find((user) => user.id === userId);
    }

    oldUsers = users;

    onDestroy(() => {
        paramsUnsubscribe();
    });
</script>

<div class="UserDetails">
    {#if selectedUser !== null}
        <img src={ selectedUser?.avatar } alt="avatar" />
    {/if}
    <p>
        <strong>Name: </strong>
        { selectedUser?.first_name } { selectedUser?.last_name }
    </p>
    <p>
        <strong>Email: </strong>
        { selectedUser?.email }
    </p>
    <span>
        <strong>Notes:</strong>
    </span>
    {#if selectedUser !== null}
        <textarea></textarea>
    {/if}
</div>
