// children/svelte-child-2/src/components/UserDetails.svelte
<style lang="scss">
  @import "src/styles/common";

  .UserDetails {
    margin: 1rem;
    padding: 2rem;
    font-size: $text-size-content;

    @include border-light;

    :global(textarea) {
      width: 100%;
      height: 10rem;
      resize: none;
    }
  }
</style>

<script>
    import { createGetSelectedUser } from './createGetSelectedUser';
    import { subscribe, updateState, getState } from 'globalStore'; // TODO refactor to be functional
    import { afterUpdate, onDestroy } from 'svelte';

    export let users = [];

    const getSelectedUser = createGetSelectedUser();
    $: selectedUser = getSelectedUser(users);
    let notes = '';

    let oldSelectedUser = null;
    $: if (oldSelectedUser !== selectedUser) {
        notes = getState().userNotes?.[selectedUser?.id] ?? '';
        oldSelectedUser = selectedUser;
    }

    const storeUnsubscribe = subscribe((state) => {
        notes = state.userNotes?.[selectedUser?.id] ?? '';
    });

    onDestroy(() => {
        storeUnsubscribe();
    });

    const updateNotes = (text) => updateState((draft) => {
        const userNotes = draft.userNotes ?? {};
        userNotes[selectedUser.id] = text;
        draft.userNotes = userNotes;
    });
</script>

<div class="UserDetails">
    {#if selectedUser !== null}
        <img src={ selectedUser?.avatar } alt="avatar" />
    {/if}
    <p>
        <strong>Name: </strong>
        { selectedUser?.first_name ?? '' } { selectedUser?.last_name ?? '' }
    </p>
    <p>
        <strong>Email: </strong>
        { selectedUser?.email ?? '' }
    </p>
    <span>
        <strong>Notes:</strong>
    </span>
    {#if selectedUser !== null}
        <textarea
                value={ notes }
                on:input={ (event) => updateNotes(event.target.value) }
        />
    {/if}
</div>

// children/react-child-1/src/components/UserDetails.js
import classes from './UserDetails.module.scss';
import { userPropType } from '../propTypes/userPropType';
import PropTypes from 'prop-types';
import { useSelectedUser } from './useSelectedUser';
import { useEffect, useState } from 'react';
import { subscribe, updateState } from 'globalStore'; // TODO refactor to be functional

export const UserDetails = (props) => {
    const [state, setState] = useState({
        notes: ''
    });
    const selectedUser = useSelectedUser(props.users);
    useEffect(() => {
        // TODO am I subscribing multiple times?
        return subscribe((state) => {
            const notes = state.userNotes?.[selectedUser?.id] ?? '';
            setState((prevState) => ({
                ...prevState,
                notes
            }));
        });
    }, [selectedUser]);

    const updateNotes = (text) => updateState((draft) => {
        const userNotes = draft.userNotes ?? {};
        userNotes[selectedUser.id] = text;
        draft.userNotes = userNotes;
    });

    return (
        <div className={ classes.UserDetails }>
            {
                selectedUser &&
                <img src={ selectedUser?.avatar } alt="avatar" />
            }
            <p>
                <strong>Name: </strong>
                { selectedUser?.first_name } { selectedUser?.last_name }
            </p>
            <p>
                <strong>Email: </strong>
                { selectedUser?.email }
            </p>
            <span>
                <strong>Notes:</strong>
            </span>
            {
                selectedUser &&
                <textarea
                    onChange={ (event) => updateNotes(event.target.value) }
                    value={ state.notes }
                />
            }
        </div>
    );
};
UserDetails.propTypes = {
    users: PropTypes.arrayOf(userPropType).isRequired
};
